[workspace]
members = [
    "crates/*",
    "mini-games",
    "tiny-adventure",
    "web3-games",
]
resolver = "2"

[workspace.dependencies]
macroquad = "0.4"
shipyard = "0.7"

[profile.dev.package.'*']
opt-level = 3
